# Renders the "❤️ Sponsor" button at the top of the repository page.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
custom:
  - https://www.paypal.com/ncp/payment/MV7WU2MHKP3P4
